#!/bin/bash

# CAUTION: this script could be dangerous!!!
# SBK automatic GRUB signing hook for Secure Boot by ALTERRQ

# Source sbk
source "/usr/local/bin/sbk" 2>/dev/null || echo "\e[1;31m[ERROR]Failed to source sbk\e[0m" | exit 1

# Source functions
source "$SBK_HOME/scripts/functions" 2>/dev/null || echo "\e[1;31m[ERROR]Failed to source functions\e[0m" | exit 1

# Source the config
source "$SBK_HOME/scripts/.config" 2>/dev/null || error_exit "Failed to source .config"

# Only proceed if certs are created
if [ $MKCERT_DONE -eq 0 ]; then
    error_exit "Signing failed. Create certificates first."
fi

# Wait a moment for the kernel installation to complete
sleep 2

# Sign GRUB
BOOTLOADER="/boot/efi/EFI/kali/grubx64.efi"
if [ -f "$BOOTLOADER" ]; then
    echo "Signing GRUB bootloader for Secure Boot..."
    sbsign "$BOOTLOADER" \
        --key "$SBK_HOME/db.key" --cert "$SBK_HOME/db.pem" \
        --output "$BOOTLOADER" && \
    echo "Successfully signed GRUB bootloader"
fi
